Repository GSG-G11/SpaceX, pull requests merged in 2022-04, with the labels that each got.

#2 Create file Structure
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/index.css
  src/index.js
Labels: Approved

#4 Create Route and Create Components NavBar and footer and style it
  package-lock.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/Footer/Footer.jsx
  src/components/Footer/footer.css
  src/components/Header/Header.jsx
  src/components/Header/header.css
  src/components/Launch/Launch.jsx
  src/components/Launch/launch.css
  src/components/Main/Main.jsx
  src/components/Main/main.css
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/navbar.css
  src/components/SingleLaunch/SingleLaunch.jsx
  src/components/SingleLaunch/singleLaunch.css
  src/index.css
  src/index.js
  src/pages/Home.jsx
  src/pages/NotFound.jsx
Labels: Approved

#8 Add Launch Components
  src/assets/background_launched.jpg
  src/assets/notFound_Launches.svg
  src/components/Footer/footer.css
  src/components/Header/Header.jsx
  src/components/Launch/Launch.jsx
  src/components/Launch/launch.css
  src/components/Launches/Launch.jsx
  src/components/Launches/Launches.jsx
  src/components/Launches/LoadingLaunches.jsx
  src/components/Launches/NotFoundLaunches.jsx
  src/components/Launches/launch.css
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/navbar.css
  src/index.css
  src/pages/Home.jsx
Labels: Awaiting Review

#11 Create details page
  .gitignore
  src/components/Footer/footer.css
  src/components/Launches/Launch.jsx
  src/components/Launches/Launches.jsx
  src/components/Launches/LoadingLaunches.jsx
  src/components/Launches/NotFoundLaunches.jsx
  src/components/Main/Main.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/navbar.css
  src/components/SingleLaunch/SingleLaunch.jsx
  src/components/SingleLaunch/singleLaunch.css
Labels: Done, Approved

#13 Create Paginations and style it, and Fix Bug in Style
  src/components/Launches/Launch.jsx
  src/components/Launches/Launches.jsx
  src/components/Launches/launch.css
  src/components/NavBar/navbar.css
  src/components/SingleLaunch/SingleLaunch.jsx
  src/components/SingleLaunch/SingleLaunchLoading.jsx
  src/components/SingleLaunch/singleLaunch.css
  src/index.css
Labels: Approved

#15 Search Component
  src/components/Filter/FilterByName.jsx
  src/components/Filter/filterByName.css
  src/components/Launches/Launches.jsx
  src/components/SingleLaunch/singleLaunch.css
Labels: Approved

#16 Fix missing Code
  public/favicon.ico
  public/favicon.jpg
  public/index.html
  src/components/Filter/FilterByName.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Launches/Launch.jsx
  src/components/Launches/Launches.jsx
  src/components/Launches/LoadingLaunches.jsx
  src/components/Launches/NotFoundLaunches.jsx
  src/index.js
  src/pages/Home.jsx
  src/pages/NotFound.jsx
Labels: Approved
